### ISSUE TITLE
Missing toolbox requirement

### ISSUE THREAD

**Issue by matejmoravec** [EvoMindLab/EDOLAB#1]
A missing toolbox requirement needs to be added to the "MATLAB support" section in the README.md file ([Statistics and Machine Learning Toolbox](https://www.mathworks.com/products/statistics.html)).

**Comment by Danial-Yazdani** [comment]
Hi,
Thank you for bringing this to our attention. 
Could you please specify which part of EDOLAB relies on the Statistics and Machine Learning Toolbox? 
Thanks

**Comment by Danial-Yazdani** [comment]
> A missing toolbox requirement needs to be added to the "MATLAB support" section in the README.md file ([Statistics and Machine Learning Toolbox](https://www.mathworks.com/products/statistics.html)).



> A missing toolbox requirement needs to be added to the "MATLAB support" section in the README.md file ([Statistics and Machine Learning Toolbox](https://www.mathworks.com/products/statistics.html)).

Hi,
Thank you for bringing this to our attention.
Could you please specify which part of EDOLAB relies on the Statistics and Machine Learning Toolbox?
Thanks

**Comment by Danial-Yazdani** [comment]
> A missing toolbox requirement needs to be added to the "MATLAB support" section in the README.md file ([Statistics and Machine Learning Toolbox](https://www.mathworks.com/products/statistics.html)).

Hi,
Thank you for bringing this to our attention.
Could you please specify which part of EDOLAB relies on the Statistics and Machine Learning Toolbox?
Thanks

**Comment by matejmoravec** [comment]
> > A missing toolbox requirement needs to be added to the "MATLAB support" section in the README.md file ([Statistics and Machine Learning Toolbox](https://www.mathworks.com/products/statistics.html)).
> 
> Hi, Thank you for bringing this to our attention. Could you please specify which part of EDOLAB relies on the Statistics and Machine Learning Toolbox? Thanks

Hi,

Using a [`normrnd`](https://www.mathworks.com/help/stats/normrnd.html) random number generator requires a Statistics and Machine Learning Toolbox.

Error message:
```
'normrnd' requires Statistics and Machine Learning Toolbox.

Error in BenchmarkGenerator_FPs (line 137)
               Problem.PeaksPosition(:,:,ii) = Problem.PeaksPosition(:,:,ii-1) + v_normed * normrnd(0,Problem.ShiftSeverity);
```

**Comment by PengMai1998** [comment]
> > > A missing toolbox requirement needs to be added to the "MATLAB support" section in the README.md file ([Statistics and Machine Learning Toolbox](https://www.mathworks.com/products/statistics.html)).
> > 
> > 
> > Hi, Thank you for bringing this to our attention. Could you please specify which part of EDOLAB relies on the Statistics and Machine Learning Toolbox? Thanks
> 
> Hi,
> 
> Using a [`normrnd`](https://www.mathworks.com/help/stats/normrnd.html) random number generator requires a Statistics and Machine Learning Toolbox.
> 
> Error message:
> 
> ```
> 'normrnd' requires Statistics and Machine Learning Toolbox.
> 
> Error in BenchmarkGenerator_FPs (line 137)
>                Problem.PeaksPosition(:,:,ii) = Problem.PeaksPosition(:,:,ii-1) + v_normed * normrnd(0,Problem.ShiftSeverity);
> ```

Hi,
Thank you for providing the information.
Could you please provide the version information for your MATLAB?
Thank you very much.

**Comment by matejmoravec** [comment]
> > > > A missing toolbox requirement needs to be added to the "MATLAB support" section in the README.md file ([Statistics and Machine Learning Toolbox](https://www.mathworks.com/products/statistics.html)).
> > > 
> > > 
> > > Hi, Thank you for bringing this to our attention. Could you please specify which part of EDOLAB relies on the Statistics and Machine Learning Toolbox? Thanks
> > 
> > 
> > Hi,
> > Using a [`normrnd`](https://www.mathworks.com/help/stats/normrnd.html) random number generator requires a Statistics and Machine Learning Toolbox.
> > Error message:
> > ```
> > 'normrnd' requires Statistics and Machine Learning Toolbox.
> > 
> > Error in BenchmarkGenerator_FPs (line 137)
> >                Problem.PeaksPosition(:,:,ii) = Problem.PeaksPosition(:,:,ii-1) + v_normed * normrnd(0,Problem.ShiftSeverity);
> > ```
> 
> Hi, Thank you for providing the information. Could you please provide the version information for your MATLAB? Thank you very much.

Hi,

Of course, I'm using the newest version of MATLAB R2023a.

**Comment by PengMai1998** [comment]
> A missing toolbox requirement needs to be added to the "MATLAB support" section in the README.md file ([Statistics and Machine Learning Toolbox](https://www.mathworks.com/products/statistics.html)).

Thank you very much for your feedback. After our investigation, we have indeed found that support from the Statistics and Machine Learning Toolbox is required. We have updated the README.md file accordingly. Please install the Statistics and Machine Learning Toolbox and run EDOLAB again. If you have any further questions, please feel free to contact us.

**Comment by PengMai1998** [comment]
Thank you again for your feedback. I will now close this issue.
