### ISSUE TITLE
One more missing toolbox requirement

### ISSUE THREAD

**Issue by matejmoravec** [EvoMindLab/EDOLAB#2]
A missing toolbox requirement needs to be added to the "MATLAB support" section in the README.md file ([Deep Learning Toolbox](https://www.mathworks.com/products/deep-learning.html)).

Error message:
```
'rands' requires Deep Learning Toolbox.

Error in ChangeReaction_AmQSO (line 40)
        Optimizer.pop(jj).X = repmat(Optimizer.pop(jj).BestPosition,Optimizer.PopulationSize,1)+ (rands(Optimizer.PopulationSize,Optimizer.Dimension)*Optimizer.ShiftSeverity);

Error in main_AmQSO (line 97)
            [Optimizer,Problem] = ChangeReaction_AmQSO(Optimizer,Problem);
```

After I installed it, everything worked like a charm. :relieved:

**Comment by Competition-hub** [comment]
Hi,
Thanks for your comment. You are right. We will modify the codes to not use rands. For now, I will add a comment to the ReadMe file to clarify this.
Thanks
Danial

**Comment by Danial-Yazdani** [comment]
Sorry, I was signed in with my other account.
I will mark it as resolved.
Cheers!
