### ISSUE TITLE
EDOLAB doesn't work via GUI

### ISSUE THREAD

**Issue by matejmoravec** [EvoMindLab/EDOLAB#3]
A new output parameter added in e212f23 (when runtime metrics were added for each algorithm) is missing in the [RunWithGUI.m](https://github.com/Danial-Yazdani/EDOLAB-MATLAB/blob/main/RunWithGUI.m) file when the optimization function `main_EDO` is called (lines 417-430).
```MATLAB
[app.Problem, ...
        app.E_bbc, ...
        app.E_o, ...
        ~, ... % missing parameter
        app.CurrentError, ...
        app.VisualizationInfo, ...
        app.Iteration] ...
        = main_EDO(app.VisualizationOverOptimization, ...
        app.PeakNumber,...
        app.ChangeFrequency, ...
        app.Dimension, ...
        app.ShiftSeverity,...
        app.EnvironmentNumber, ...
        app.RunNumber, ...
        app.BenchmarkName);
```

UPDATE:
The same goes for lines 490-504.

**Comment by Danial-Yazdani** [comment]
Hi,

Thank you for bringing this issue to our attention—we appreciate your feedback!

We’re currently investigating the cause and will work to address it by the end of this week.

Best regards,
Danial

**Comment by PengMai1998** [comment]
Hi,

Thank you for your patience. I've resolved the issue regarding the missing runtime metric in RunWithGUI.m. The changes have been implemented, and the runtime metric is now correctly displayed in the GUI.

Please feel free to reach out if you encounter any further issues or have additional feedback.

Best regards,
Mai Peng

**Comment by Danial-Yazdani** [comment]
Thanks Mai for addressing the issue.
Danial
